module.exports = {
  AskorSayNo: {
    original: require("../../assets/skills/AskorSayNo/AskorSayNo-Original.mp4"),
    360: require("../../assets/skills/AskorSayNo/AskorSayNo-360.mp4"),
    540: require("../../assets/skills/AskorSayNo/AskorSayNo-540.mp4"),
    720: require("../../assets/skills/AskorSayNo/AskorSayNo-720.mp4"),
  },
  Balance: {
    original: require("../../assets/skills/Balance/Balance-Original.mp4"),
    360: require("../../assets/skills/Balance/Balance-360.mp4"),
    540: require("../../assets/skills/Balance/Balance-540.mp4"),
    720: require("../../assets/skills/Balance/Balance-720.mp4"),
  },
  Breathe: {
    original: require("../../assets/skills/Breathe/Breathe-Original.mp4"),
    360: require("../../assets/skills/Breathe/Breathe-360.mp4"),
    540: require("../../assets/skills/Breathe/Breathe-540.mp4"),
    720: require("../../assets/skills/Breathe/Breathe-720.mp4"),
  },
  BuildPositiveExperiences: {
    original: require("../../assets/skills/BuildPositiveExperiences/BuildPositiveExperiences-Original.mp4"),
    360: require("../../assets/skills/BuildPositiveExperiences/BuildPositiveExperiences-360.mp4"),
    540: require("../../assets/skills/BuildPositiveExperiences/BuildPositiveExperiences-540.mp4"),
    720: require("../../assets/skills/BuildPositiveExperiences/BuildPositiveExperiences-720.mp4"),
  },
  CrystalCLEAR: {
    original: require("../../assets/skills/CrystalCLEAR/CrystalCLEAR-Original.mp4"),
    360: require("../../assets/skills/CrystalCLEAR/CrystalCLEAR-360.mp4"),
    540: require("../../assets/skills/CrystalCLEAR/CrystalCLEAR-540.mp4"),
    720: require("../../assets/skills/CrystalCLEAR/CrystalCLEAR-720.mp4"),
  },
  Distract: {
    original: require("../../assets/skills/Distract/Distract-Original.mp4"),
    360: require("../../assets/skills/Distract/Distract-360.mp4"),
    540: require("../../assets/skills/Distract/Distract-540.mp4"),
    720: require("../../assets/skills/Distract/Distract-720.mp4"),
  },
  DoOneThing: {
    original: require("../../assets/skills/DoOneThing/DoOneThing-Original.mp4"),
    360: require("../../assets/skills/DoOneThing/DoOneThing-360.mp4"),
    540: require("../../assets/skills/DoOneThing/DoOneThing-540.mp4"),
    720: require("../../assets/skills/DoOneThing/DoOneThing-720.mp4"),
  },
  DRIFT: {
    original: require("../../assets/skills/DRIFT/DRIFT-Original.mp4"),
    360: require("../../assets/skills/DRIFT/DRIFT-360.mp4"),
    540: require("../../assets/skills/DRIFT/DRIFT-540.mp4"),
    720: require("../../assets/skills/DRIFT/DRIFT-720.mp4"),
  },
  EndorMend: {
    original: require("../../assets/skills/EndorMend/EndorMend-Original.mp4"),
    360: require("../../assets/skills/EndorMend/EndorMend-360.mp4"),
    540: require("../../assets/skills/EndorMend/EndorMend-540.mp4"),
    720: require("../../assets/skills/EndorMend/EndorMend-720.mp4"),
  },
  FACTOPINION: {
    original: require("../../assets/skills/FACTOPINION/FACTOPINION-Original.mp4"),
    360: require("../../assets/skills/FACTOPINION/FACTOPINION-360.mp4"),
    540: require("../../assets/skills/FACTOPINION/FACTOPINION-540.mp4"),
    720: require("../../assets/skills/FACTOPINION/FACTOPINION-720.mp4"),
  },
  Focus: {
    original: require("../../assets/skills/Focus/Focus-Original.mp4"),
    360: require("../../assets/skills/Focus/Focus-360.mp4"),
    540: require("../../assets/skills/Focus/Focus-540.mp4"),
    720: require("../../assets/skills/Focus/Focus-720.mp4"),
  },
  ITWILLPASS: {
    original: require("../../assets/skills/ITWILLPASS/ITWILLPASS-Original.mp4"),
    360: require("../../assets/skills/ITWILLPASS/ITWILLPASS-360.mp4"),
    540: require("../../assets/skills/ITWILLPASS/ITWILLPASS-540.mp4"),
    720: require("../../assets/skills/ITWILLPASS/ITWILLPASS-720.mp4"),
  },
  KeepCalmandCarryOn: {
    original: require("../../assets/skills/KeepCalmandCarryOn/KeepCalmandCarryOn-Original.mp4"),
    360: require("../../assets/skills/KeepCalmandCarryOn/KeepCalmandCarryOn-360.mp4"),
    540: require("../../assets/skills/KeepCalmandCarryOn/KeepCalmandCarryOn-540.mp4"),
    720: require("../../assets/skills/KeepCalmandCarryOn/KeepCalmandCarryOn-720.mp4"),
  },
  Listen: {
    original: require("../../assets/skills/Listen/Listen-Original.mp4"),
    360: require("../../assets/skills/Listen/Listen-360.mp4"),
    540: require("../../assets/skills/Listen/Listen-540.mp4"),
    720: require("../../assets/skills/Listen/Listen-720.mp4"),
  },
  MaintainRelationship: {
    original: require("../../assets/skills/MaintainRelationship/MaintainRelationship-Original.mp4"),
    360: require("../../assets/skills/MaintainRelationship/MaintainRelationship-360.mp4"),
    540: require("../../assets/skills/MaintainRelationship/MaintainRelationship-540.mp4"),
    720: require("../../assets/skills/MaintainRelationship/MaintainRelationship-720.mp4"),
  },
  NAMEtheEMOTION: {
    original: require("../../assets/skills/NAMEtheEMOTION/NAMEtheEMOTION-Original.mp4"),
    360: require("../../assets/skills/NAMEtheEMOTION/NAMEtheEMOTION-360.mp4"),
    540: require("../../assets/skills/NAMEtheEMOTION/NAMEtheEMOTION-540.mp4"),
    720: require("../../assets/skills/NAMEtheEMOTION/NAMEtheEMOTION-720.mp4"),
  },
  Observe: {
    original: require("../../assets/skills/Observe/Observe-Original.mp4"),
    360: require("../../assets/skills/Observe/Observe-360.mp4"),
    540: require("../../assets/skills/Observe/Observe-540.mp4"),
    720: require("../../assets/skills/Observe/Observe-720.mp4"),
  },
  OppositeAction: {
    original: require("../../assets/skills/OppositeAction/OppositeAction-Original.mp4"),
    360: require("../../assets/skills/OppositeAction/OppositeAction-360.mp4"),
    540: require("../../assets/skills/OppositeAction/OppositeAction-540.mp4"),
    720: require("../../assets/skills/OppositeAction/OppositeAction-720.mp4"),
  },
  PACEandPLAN: {
    original: require("../../assets/skills/PACEandPLAN/PACEandPLAN-Original.mp4"),
    360: require("../../assets/skills/PACEandPLAN/PACEandPLAN-360.mp4"),
    540: require("../../assets/skills/PACEandPLAN/PACEandPLAN-540.mp4"),
    720: require("../../assets/skills/PACEandPLAN/PACEandPLAN-720.mp4"),
  },
  Reflect: {
    original: require("../../assets/skills/Reflect/Reflect-Original.mp4"),
    360: require("../../assets/skills/Reflect/Reflect-360.mp4"),
    540: require("../../assets/skills/Reflect/Reflect-540.mp4"),
    720: require("../../assets/skills/Reflect/Reflect-720.mp4"),
  },
  RESPECT: {
    original: require("../../assets/skills/RESPECT/RESPECT-Original.mp4"),
    360: require("../../assets/skills/RESPECT/RESPECT-360.mp4"),
    540: require("../../assets/skills/RESPECT/RESPECT-540.mp4"),
    720: require("../../assets/skills/RESPECT/RESPECT-720.mp4"),
  },
  RightNow: {
    original: require("../../assets/skills/RightNow/RightNow-Original.mp4"),
    360: require("../../assets/skills/RightNow/RightNow-360.mp4"),
    540: require("../../assets/skills/RightNow/RightNow-540.mp4"),
    720: require("../../assets/skills/RightNow/RightNow-720.mp4"),
  },
  SELFcare: {
    original: require("../../assets/skills/SELFcare/SELFcare-Original.mp4"),
    360: require("../../assets/skills/SELFcare/SELFcare-360.mp4"),
    540: require("../../assets/skills/SELFcare/SELFcare-540.mp4"),
    720: require("../../assets/skills/SELFcare/SELFcare-720.mp4"),
  },
  SieveorSponge: {
    original: require("../../assets/skills/SieveorSponge/SieveorSponge-Original.mp4"),
    360: require("../../assets/skills/SieveorSponge/SieveorSponge-360.mp4"),
    540: require("../../assets/skills/SieveorSponge/SieveorSponge-540.mp4"),
    720: require("../../assets/skills/SieveorSponge/SieveorSponge-720.mp4"),
  },
  Soothe: {
    original: require("../../assets/skills/Soothe/Soothe-Original.mp4"),
    360: require("../../assets/skills/Soothe/Soothe-360.mp4"),
    540: require("../../assets/skills/Soothe/Soothe-540.mp4"),
    720: require("../../assets/skills/Soothe/Soothe-720.mp4"),
  },
  STOPP: {
    original: require("../../assets/skills/STOPP/STOPP-Original.mp4"),
    360: require("../../assets/skills/STOPP/STOPP-360.mp4"),
    540: require("../../assets/skills/STOPP/STOPP-540.mp4"),
    720: require("../../assets/skills/STOPP/STOPP-720.mp4"),
  },
  TalktheTalk: {
    original: require("../../assets/skills/TalktheTalk/TalktheTalk-Original.mp4"),
    360: require("../../assets/skills/TalktheTalk/TalktheTalk-360.mp4"),
    540: require("../../assets/skills/TalktheTalk/TalktheTalk-540.mp4"),
    720: require("../../assets/skills/TalktheTalk/TalktheTalk-720.mp4"),
  },
  TheFIZZ: {
    original: require("../../assets/skills/TheFIZZ/TheFIZZ-Original.mp4"),
    360: require("../../assets/skills/TheFIZZ/TheFIZZ-360.mp4"),
    540: require("../../assets/skills/TheFIZZ/TheFIZZ-540.mp4"),
    720: require("../../assets/skills/TheFIZZ/TheFIZZ-720.mp4"),
  },
  Thinking: {
    original: require("../../assets/skills/Thinking/Thinking-Original.mp4"),
    360: require("../../assets/skills/Thinking/Thinking-360.mp4"),
    540: require("../../assets/skills/Thinking/Thinking-540.mp4"),
    720: require("../../assets/skills/Thinking/Thinking-720.mp4"),
  },
  ThisMoment: {
    original: require("../../assets/skills/ThisMoment/ThisMoment-Original.mp4"),
    360: require("../../assets/skills/ThisMoment/ThisMoment-360.mp4"),
    540: require("../../assets/skills/ThisMoment/ThisMoment-540.mp4"),
    720: require("../../assets/skills/ThisMoment/ThisMoment-720.mp4"),
  },
  TurnTheMind: {
    original: require("../../assets/skills/TurnTheMind/TurnTheMind-Original.mp4"),
    360: require("../../assets/skills/TurnTheMind/TurnTheMind-360.mp4"),
    540: require("../../assets/skills/TurnTheMind/TurnTheMind-540.mp4"),
    720: require("../../assets/skills/TurnTheMind/TurnTheMind-720.mp4"),
  },
  VALUES: {
    original: require("../../assets/skills/VALUES/VALUES-Original.mp4"),
    360: require("../../assets/skills/VALUES/VALUES-360.mp4"),
    540: require("../../assets/skills/VALUES/VALUES-540.mp4"),
    720: require("../../assets/skills/VALUES/VALUES-720.mp4"),
  },
  WiseMind: {
    original: require("../../assets/skills/WiseMind/WiseMind-Original.mp4"),
    360: require("../../assets/skills/WiseMind/WiseMind-360.mp4"),
    540: require("../../assets/skills/WiseMind/WiseMind-540.mp4"),
    720: require("../../assets/skills/WiseMind/WiseMind-720.mp4"),
  },
};
